apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: calc
  annotations:
    version: v0.0.1
    description: 'An application with a custom calculation provider and component built for extending wasmCloud with custom capabilities'
spec:
  components:
    - name: calc-component
      type: component
      properties:
        image: file://./calc-component/build/custom_template_test_component.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 5
        # Link the component to the provider on wasmcloud:calculation/calculator
        - type: link
          properties:
            target:
              name: calc-provider
            namespace: wasmcloud
            package: calculation
            interfaces: [calculator]
        - type: link
          properties:
            target:
              name: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    # Capability provider - calc provider:
    - name: calc-provider
      type: capability
      properties:
        image: file://./calc-provider/build/wasmcloud-provider-custom-template.par.gz
        config:
          - name: provider-config
            properties:
              foo: bar
      traits:
        # Link the provider to the component on wasmcloud:example/process-data
        - type: link
          properties:
            target:
              name: calc-component
            namespace: wasmcloud
            package: calculation
            interfaces: [process-data]

# Add a capability provider that implements `wasmcloud:messaging` using NATS
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.27.0
        ## To configure OTEL integration for this provider specifically, uncomment the lines below
        # config:
        #   - name: otel
        #     properties:
        #       otel_exporter_otlp_endpoint: "http://all-in-one:4318"
        #       otel_exporter_otlp_traces_endpoint: "http://traces-backend/v1/traces"
        #       otel_exporter_otlp_metrics_endpoint: "http://metrics-backend/v1/metrics"
        #       otel_exporter_otlp_logs_endpoint: "http://logs-backend/v1/logs"
      traits:
        # Since the `nats` capability provider calls an component to handle messages
        # coming over subscriptions, this provider needs a unidirectional link to the
        # component that will be called.
        #
        # Here we link the `nats` provider (the "source"), to the `echo` component (the "target"),
        # so that so the provider can deliver messages to the component (by invoking the wasmcloud:messaging/handler interface) .
        - type: link
          properties:
            target:
              name: calc-component
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              config:
                - name: simple-subscription
                  properties:
                    subscriptions: wasmcloud.echo
